# Generated by Django 2.1 on 2018-09-21 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='store.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartTreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='trees', to='store.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=100000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('fun_facts', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('maintenance', models.CharField(choices=[('HG', 'High Maintenance'), ('LW', 'Low Maintenance'), ('MD', 'Medium Maintenance')], max_length=2)),
                ('height', models.FloatField()),
                ('growth_rate', models.CharField(choices=[('FR', 'Fast Growth'), ('LR', 'Medium Growth'), ('SR', 'Slow Growth')], max_length=2)),
                ('year_one', models.CharField(max_length=100000)),
                ('year_two', models.CharField(max_length=100000)),
                ('year_three', models.CharField(max_length=100000)),
                ('year_five', models.CharField(max_length=100000)),
                ('year_ten', models.CharField(max_length=100000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trees', to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='store.Wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistTreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tree')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='trees', to='store.Wishlist')),
            ],
        ),
        migrations.AddField(
            model_name='carttreeitem',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tree'),
        ),
        migrations.AddField(
            model_name='cartproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
    ]
