# Generated by Django 2.1 on 2018-09-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='carttreeitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='wishlistproductitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlisttreeitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='store.Wishlist'),
        ),
    ]
