# Generated by Django 2.1 on 2018-10-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180925_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlisttreeitem',
            name='qty',
        ),
    ]
